### ISSUE TITLE
Search about calories

### ISSUE THREAD

**Issue by jorgelisboa** [jorgelisboa/calorie-controller#1]
## Everyone needs to search about the calories, because everyone will work in the project, and we need to know every detail to use in our app.

Some things that we can search for example:

- [x] What is a calorie?
- [x] What do we use calories for?
- [x] Amount of calories we need
- [x] How to calculate food calories?
- [x] What is IMC?

### ATTEMPTION

If you search any thing, get the URL, create the bibliographic reference, and paste/write the information in our comments.

**Comment by Minuttii** [comment]
Como calcular as calorias dos alimentos?

Para isso, devemos multiplicar a quantidade, em gramas, gorduras, proteínas e carboidratos de cada porção do alimento, pelo seu respectivo valor calórico.
(1 grama de gordura = 9 calorias, 1 grama de carboidrato = 4 calorias ,  1 grama de proteína = 4 calorias).


O que é IMC?

O IMC (Índice de Massa Corporal), consiste no cálculo que se utiliza para avaliação se a pessoa está dentro do seu peso ideal em relação à altura. Assim, de acordo com o valor do resultado de IMC, a pessoa pode saber se está dentro do peso ideal, acima ou abaixo do peso desejado.
Fórmula: Peso ÷ (altura x altura).


https://www.tuasaude.com/o-que-sao-calorias/#:~:text=Para%20calcular%20as%20calorias%20dos,fornecem%204%20calorias%20por%20grama.
https://www.tuasaude.com/imc/

**Comment by jorgelisboa** [comment]
O que é uma caloria?

Caloria (cal) é uma unidade de medida de energia e tem sido geralmente utilizada para definir o valor energético dos alimentos. A caloria é uma medida que não pertence ao Sistema Internacional de Unidades (SIU) sendo o Joule a unidade padronizada pelo SIU para medição de energia. Foi definido que 1 caloria é igual a 4,1868 J (joules).

Para garantir a sobrevivência, os seres humanos necessitam ingerir caloria. Todos os alimentos são fontes de energia pois possuem calorias (a quantidade varia de acordo com o alimento).

**Comment by jorgelisboa** [comment]
A **taxa metabólica basal** (TMB) é a quantidade de calorias que seu corpo queima para se manter vivo. Portanto, este número é específico do indivíduo e determinado por vários fatores, incluindo altura, peso e idade.

**Qual é o seu fator de atividade (FA)?**
Agora, calcule o quanto o seu corpo gasta para manter o seu peso atual, levando em conta a sua rotina de atividades físicas.

**Quantas calorias devemos consumir por dia?**
Assim, para descobrir quantas calorias o seu organismo necessita diariamente basta multiplicar a sua taxa de metabolismo basal pelo fator de atividade (**TMB** X **FA**).

[Referências quantas calorias devemos consumir](https://vitat.com.br/calorias-dia/)
